function hsurf = mysurf(XG, YG, ZG, varargin)
% hsurf = mysurf(x, y, z)

hs = surf(XG, YG, ZG,...
    'linestyle','none',...
    'FaceColor','interp',...
    'FaceLighting','gouraud',...
    'EdgeLighting','none',...
    'DiffuseStrength',0.9,...
    'SpecularStrength',0.5,...
    'SpecularColorReflectance',0.5,...
    varargin{:});

camlight left;
grid on;

if nargout > 0,
    hsurf = hs;
end
