function CMDID = IntMetComCMD(strCommand)
% CMDID = IntMetComCMD(strCommand)
%
% CMDID = identifier corresponding to strCommand for use with IntMetCom
% CMDID = IntMetComCMD() with no input argument returns a struct listing
% all of the available commands.
%
%     !! command definitions
%     INTEGER, PARAMETER :: CMD_WriteWavefrontUNF  = 1
%     INTEGER, PARAMETER :: CMD_ReadWavefrontUNF   = 2
%     INTEGER, PARAMETER :: CMD_ApplyMaskRotate    = 3
%     INTEGER, PARAMETER :: CMD_CreateGausSource   = 4
%     INTEGER, PARAMETER :: CMD_CreateTophatSource = 5
%     INTEGER, PARAMETER :: CMD_Propagate          = 6
%     INTEGER, PARAMETER :: CMD_CornerCube         = 7
%     INTEGER, PARAMETER :: CMD_focuslens          = 8
%     INTEGER, PARAMETER :: CMD_ClipCirc           = 9
%     INTEGER, PARAMETER :: CMD_Heterodyne         = 10
%     INTEGER, PARAMETER :: CMD_CopyWavefront      = 11
%     INTEGER, PARAMETER :: CMD_WavefrontPower     = 12
%     INTEGER, PARAMETER :: CMD_ClipPoly           = 13
%     INTEGER, PARAMETER :: CMD_ApplyMaskPoly      = 14
%     INTEGER, PARAMETER :: CMD_SumWavefront       = 15
%     INTEGER, PARAMETER :: CMD_ThinLens           = 16
%     INTEGER, PARAMETER :: CMD_ApplyMaskTilt      = 17
%     INTEGER, PARAMETER :: CMD_CopyWavefrontAmp   = 18

sCMDID = struct(...
    'WriteWavefrontUNF',1,...
    'ReadWavefrontUNF',2,...
    'ApplyMaskRotate',3,...
    'CreateGausSource',4,...
    'CreateTophatSource',5,...
    'Propagate',6,...
    'CornerCube',7,...
    'FocusLens',8,...
    'ClipCirc',9,...
    'Heterodyne',10,...
    'CopyWavefront',11,...
    'WavefrontPower',12,...
    'ClipPoly',13,...
    'ApplyMaskPoly',14,...
    'SumWavefront',15,...
    'ThinLens',16,...
    'ApplyMaskTilt',17,...
    'CopyWavefrontAmp',18);

if nargin == 0,
    CMDID = sCMDID;
else
    CMDID = sCMDID.(strCommand);
end

end