function structAsphere = IntMetCom_ReflectAsphere(h,Asphere)
% structAsphere = IntMetCom_ReflectAsphere(h,Asphere)
% 
% structAsphere = IntMetCom_ReflectAsphere;
%    returns a structure with all the fields set to default values
%
% IntMetCom_CornerCube(h,Asphere) invokes the ReflectAsphere method in the
% interface h, using the parameters stored in the struct Asphere
%
% The fields in the Asphere structure are:
%    radius = radius of curvature, positive radius makes a collimated beam
%        diverge upon reflection (default = 1)
%    k = conic constant:  0 => sphere (default), -1 => parabola, etc.)
%    diameter = diameter of circular mirror aperture (default = 1)
%    xc  = vertex offset in x (default = 0)
%    yc  = vertex offset in y (default = 0)
%    aoi = incidence angle measured at the surface's vertex (default = 0)
%    azimuth = The plane of incidence makes an angle "azimuth" with respect
%        to the beam grid x-axis (default = 0)
%    applycurv =  1 (default) => explicitly apply phase curvature to the
%        wavefront, 0 => maintain separate wavefront curvature number

unitsdefinitions;

switch nargin,
    case 0,
        % return default struct if no input args
        structAsphere = struct(...
            'radius',1,...
            'k',0,...
            'diameter',1,...
            'xc',0,...
            'yc',0,...
            'aoi',0,...
            'azimuth',0,...
            'applycurv',1 );
        return;
    case 2,
        h.ReflectAsphere(...
            Asphere.radius,...
            Asphere.k,...
            Asphere.diameter,...
            Asphere.xc,...
            Asphere.yc,...
            Asphere.aoi,...
            Asphere.azimuth,...
            Asphere.applycurv );
        
    otherwise,
        error('IntMetCom_CornerCube: invalid # of arguments');
        
end % end switch
